name: Add bugs to bugs project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        id: addItem
        with:
          project-url: https://github.com/users/gillian-meilisearch/projects/1
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label-operator: OR

      - uses: kalgurn/update-project-item-status@main
        with:
          project-url: https://github.com/users/gillian-meilisearch/projects/1
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          item-id: ${{ steps.addItem.outputs.itemId }}
          status: "Triage"