name: "Add Issue/PR to Project"
on:
  issues:
    types: [opened]

jobs:
  add_to_project:
    name: Add to Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: austenstone/project-add@main
        with:
          user: leapinleprechaun
          project-number: 1
          github-token: "${{ secrets.PROJECT_PAT }}"
        id: project-add
      - uses: austenstone/project-update@main
        with:
          user: leapinleprechaun
          project-number: 1
          github-token: "${{ secrets.PROJECT_PAT }}"
          item-id: ${{ steps.project-add.outputs.id }}
          field-names: Status,testing
          field-values: todo,test2