name: Github Context

on:
  issues:
    types: [assigned]

jobs:
  github-context:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }} | jq