name: Projects Test

on:
  issues:
    types: [assigned]

jobs:
  projects-test:
    runs-on: ubuntu-latest
    steps:
      - name: "dump project fields"
        uses: EndBug/project-fields@v1
        id: fields
        with:
          fields: select
          github_token: ${{ secrets.PROJECT_PAT }}
          project_url: https://github.com/users/gillianorg/projects/1
      - run: echo ${{ steps.fields.outputs.values }}