name: Projects Test

on:
  issues:
    types: [assigned]

jobs:
  github-context:
    runs-on: ubuntu-latest
    steps:
      - name: "dump project fields"
        uses: EndBug/project-fields@v1
        id: fields
        with:
          fields: text,number,date,select
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          project_url: https://github.com/orgs/gillianorg/projects/1
      - run: echo ${{ steps.fields.outputs.values }}